### ISSUE TITLE
前两天就在想的，真就出来了

### ISSUE THREAD

**Issue by xulihang** [lhproject/campuspiders#1]
前几天逛北邮人论坛，看到有人用scrapy写分析网站热门度的软件，才知道这个爬虫框架。江大的网站都没有api，写个爬虫很实用，不管是微信，食堂墙还是手机app都用得着吧。@CodeFalling，@dark-flame-master。

**Comment by xcodebuild** [comment]
恩我有见过的，但其实学校大部分网页不需要这么麻烦，直接抓取网页再用正则表达式匹配就可以了……scrapy是针对网站写的爬虫框架，用于类似数据挖掘等用途。而我们主要针对某个网页的特定信息（有用的数据）而已，所以没有采用
2014年1月19日 上午11:37于 "xulihang" notifications@github.com写道：

**Comment by xulihang** [comment]
哦，对。不用scrapy，光用urllib2和re就够用了。

**Comment by xen0n** [comment]
我写了个[`campuspiders`](https://github.com/jnrainerds/campuspiders)项目, 这块信息爬虫的工作都在这里进行, **用Scrapy**.

你们的工作之后都基于这个库进行, 工作效率特别高. 始终需要向你们强调的一点是**不要因为当前的问题规模小而放弃使用专用框架**, 不然会后悔的. @CodeFalling 你需要注意一下工作思路

**Comment by xcodebuild** [comment]
(・●・)这样么……可是我正在回去的路上，回去就要和小伙伴们玩耍了，那好我来之后研究研究（原来数媒的数据也是这么拿到的）
2014年1月19日 上午11:59于 "Wang Xuerui" notifications@github.com写道：

**Comment by xen0n** [comment]
好吧我估计你们注意到Scrapy就是因为我昨晚上推了这个项目...  简单来说就算对于小网站, Scrapy也有好处:
- **并行抓取**, 提高带宽利用率, 间接大幅度提升处理效率
- **解析正确性与高效性**, 使用lxml库高效 (C语言代码) 解析HTML内容. 能处理大多数不规范的HTML片段, 正确得到HTML树. **不要用正则处理HTML**
- **可维护性** 使用CSS选择器或者XPath或者直接使用lxml API取得内容, 不用维护正则, 可读性高, 容易调整
- **流水线形式处理记录**, 高模块化, 高解耦 (组件之间只有松散联系, 方便替换/增加/去除等变化), 同时对记录的处理方式灵活多样
- **行业最佳实践** 有庞大的社区, 中国使用者也数量众多 (大量中小型电商网站数据源就靠这个爬的), 遇到问题总能得到答案 (或者被指引到文档的正确章节). 而且多年的生产环境积累使得大量常见问题在框架里得到良好解决, 自己造轮子就得自己从头走一遍, **适合学习不适合生产**

先想到这么多, 你们感受一下

**Comment by xen0n** [comment]
@CodeFalling 原来你一直在学校啊0 0 表示同情

**Comment by xen0n** [comment]
尼玛原来就是在这项目里头发的issue... 我脑抽了 (学工处网站貌似无法访问, 很伤心)

**Comment by xcodebuild** [comment]
没有…一直在杭州这边，现在在回老家的路上
2014年1月19日 下午12:09于 "Wang Xuerui" notifications@github.com写道：

**Comment by xen0n** [comment]
额好吧= =那里估计没网, 那你可以afk一段时间了.

话说你回来之后把你的blackbox代码全都开源了吧, 因为你用`.gitignore`忽略它们的话会造成那些文件**不受版本控制**, 万一改坏了后果很严重, 而且我这几天想了一下**就算你开源了想拿这个找我们茬的人他也看不懂**, 其实纠结这些东西没有意义, 还不如都放出来呢...

而且人家网站放在那里就是等着人爬的, 帮他们把他们站上的东西有效宣传出去他们高兴还来不及呢 (这个他们指行政人员)

**Comment by xcodebuild** [comment]
好的  等我回去就整理下开放  坐车快坐出内伤了，回去有网可是网吧没有git 23333
2014年1月19日 下午12:18于 "Wang Xuerui" notifications@github.com写道：

**Comment by xen0n** [comment]
问题已经解决, 结帖, 有事新开issue
